### ISSUE TITLE
Decimals > 18 will cause a revert for normalizedCollateralAmount

### ISSUE THREAD

**Issue by 0xMilenov** [VIS-2/3adao-01-24#1]
**Context:** [AuctionManager.sol](https://github.com/3A-DAO/3a-borrowing-protocol/blob/main/contracts/AuctionManager.sol#L178)

**Impact** The protocol allows tokens with any number of decimals to be whitelisted, this could severely compromise auction integrity and financial security.

**Description** "[3A DAO relies on these underlying factors](https://docs.3adao.org/3a-protocol/whitelisting-criteria/mandatory-requirements) to assess a protocol’s creditworthiness and decides if a token can get whitelisted as collateral. This risk model is going to be the backbone of 3A’s long-term success" 

We see that the whitelisting criteria missing a decimal limit for tokens!

The `newAuction` function inside `AuctionManager` is vulnerable when normalizing collateral amounts. This issue arises if a collateral token with more than 18 decimals is used, **leading to a revert in the normalization calculation.** 

```solidity
uint256 _normalizedCollateralAmount = _collateralAmount * (10 ** (18 -  _priceFeed.decimals(address(collateralToken))));
```
Proofs - [Secureum Mind Map](https://github.com/x676f64/secureum-mind_map/blob/master/content/7.%20Audit%20Findings%20101/Tokens%20with%20more%20than%2018%20decimal%20points%20will%20cause%20issues.md) & [Consensys](https://consensys.io/diligence/audits/2021/03/defi-saver/#tokens-with-more-than-18-decimal-points-will-cause-issues)

**Recommendation** Implement a check to ensure collateral tokens do not exceed 18 decimals:
```solidity
require(_priceFeed.decimals(address(collateralToken)) <= 18, "Token decimals exceed limit");
```

Fixed: [cd918de22d96b4a70e04ed173d49aaf168e65529](https://github.com/3A-DAO/3a-borrowing-protocol/commit/cd918de22d96b4a70e04ed173d49aaf168e65529)

**Comment by bytes0xcr6** [comment]
To add an extra layer of security we have added you recommendation to avoid listing tokens with higher decimals than 18 and the decimals will be checked internally by the contract to the ERC20 contract.

Fix: https://github.com/bonq-ch/3a-borrowing-protocol/commit/f3f52cfda2a5aee2ff1c390d077ff1db7a69c402
