### ISSUE TITLE
Some tokens don't support approve `type(uint256).max` amount

### ISSUE THREAD

**Issue by 0xMilenov** [VIS-2/3adao-01-24#11]
**Context:** [LiquidationRouter.sol](https://github.com/3A-DAO/3a-borrowing-protocol/blob/816da9674b8e16802eb50478941dde60a2b8db7b/contracts/LiquidationRouter.sol#L147-L159), [AuctionManager.sol](https://github.com/3A-DAO/3a-borrowing-protocol/blob/816da9674b8e16802eb50478941dde60a2b8db7b/contracts/AuctionManager.sol#L262)

**Impact** The issue can cause transaction failures for tokens like UNI or COMP that do not support unlimited approval amounts, potentially impacting the protocol's liquidity operations, on `Ethereum Mainnet`.

**Description** Some tokens doesn't support approve spender type(uint256).max amount. So the `addSeizedCollateral` will not work for some tokens like UNI or COMP and will revert when approve type(uint256).max amount. It has many examples like this [one](https://solodit.xyz/issues/m-3-universalapprovemax-will-not-work-for-some-tokens-that-dont-support-approve-typeuint256max-amount-sherlock-dodo-dodo-git)

```solidity
function addSeizedCollateral(address _collateral, uint256 _amount) external onlyVault {
    IERC20(_collateral).safeTransferFrom(msg.sender, address(this), _amount);

    IERC20(_collateral).safeApprove(stabilityPool, 0);
    IERC20(_collateral).safeApprove(stabilityPool, type(uint256).max);

    IERC20(_collateral).safeApprove(auctionManager, 0);
    IERC20(_collateral).safeApprove(auctionManager, type(uint256).max);

    collateralSet.add(_collateral);
    collateral[_collateral] += _amount;
    emit SeizedCollateralAdded(_collateral, vaultFactory, msg.sender, _amount);
}
```

**Recommendation** Consider approving the exact amount that needs to be transferred or adding an external function that allows the revocation of approvals.

Fixed: [80923dbebe3fb2911ab9571e58bc9396177b8d69](https://github.com/3A-DAO/3a-borrowing-protocol/commit/80923dbebe3fb2911ab9571e58bc9396177b8d69)

**Comment by bytes0xcr6** [comment]
As we are planning to launch to other chains, we may be in the situation where we deal with tokens that don´t allow max uint256, The change is just to approve the required amount.

Fix commit: https://github.com/bonq-ch/3a-borrowing-protocol/commit/f90dbaf8044490cb8327b205d1931841efc72a2b
