### ISSUE TITLE
Prefer `call()` over `transfer()` for address payable in `VaultFactory`

### ISSUE THREAD

**Issue by 0xMilenov** [VIS-2/3adao-01-24#16]
**Context:** [VaultFactory.sol](https://github.com/3A-DAO/3a-borrowing-protocol/tree/main/contracts/VaultFactory.sol#L194)

**Description** Utilizing the outdated `transfer()` function on an address can lead to transaction failures due to the 2300 gas stipend.

The use of the deprecated `transfer()` function for an address will inevitably make the transaction fail when:

The claimer smart contract does not implement a payable function.
The claimer smart contract does implement a payable fallback which uses more than 2300 gas unit.
The claimer smart contract implements a payable fallback function that needs less than 2300 gas units but is called through proxy, raising the call's gas usage above 2300.

Additionally, using higher than 2300 gas might be mandatory for some multisig wallets.

[`Consensys: Don't use '.transfer' or '.send'](https://consensys.github.io/smart-contract-best-practices/development-recommendations/general/external-calls/#:~:text=See%20SWC%2D107-,Don%27t%20use%20transfer()%20or%20send().,is%20recommended%20that%20you%20use%20the%20checks%2Deffects%2Dinteractions%20pattern.,-Handle%20errors%20in)

It have many confirmed issues like this one, [exmaple](https://github.com/code-423n4/2022-04-backd-findings/issues/52)

```solidity
   payable(_to).transfer(_amount);
```

**Recommendation** Opting for the `call()` function is recommended in such scenarios to circumvent this issue.

Fixed: [d5794becad48f301bb06c896b455c63949252709](https://github.com/3A-DAO/3a-borrowing-protocol/commit/d5794becad48f301bb06c896b455c63949252709)

**Comment by bytes0xcr6** [comment]
Fix: https://github.com/bonq-ch/3a-borrowing-protocol/commit/d16702fa427af331b63d5df09729d942a3e6c761
